### ISSUE TITLE
Placeable Dice Table Use Nodes inaccessable

### ISSUE THREAD

**Issue by Anatida** [Beamdog/nwn-issues#110] opened 2020-07-08 17:15 UTC
**Description**

In testing the Dicetable  placeable from the Tyrants Art Pack, the table is inaccessible to player characters and can not be 'used'.

**To Reproduce**

 - Place the placeable Dicetable.
 - Set the dicetable to be 'useable'.
 - Enter the game as player attempt to use the table.
-- Cause: The two use nodes are in the center of the walkmesh where they can not be accessed.

**Specifics**

 - Game build 8193.13
 - OS Windows 10
 - Distro platform Steam
 - This is tested by using the Tyrants' Artpack contents in a hak on Arelith PW server.

![image](https://user-images.githubusercontent.com/50813811/86949523-636fcf00-c114-11ea-9bfd-e1d8c0fc4a59.png)

**Comment by Bill-Harper** [comment] 2020-07-13 15:32
![dicetable_use-nodes_still-wont-work](https://user-images.githubusercontent.com/53191846/87323094-495f3380-c4fc-11ea-816d-7c092d319182.png)

This one is proving to be a real chore. I've tested a couple dozen variations on the above screenshot, but bottom line it keeps aiming for dead center no matter what I do (i.e ignoring all the Use Nodes). I'll keep trying...

**Comment by Bill-Harper** [comment] 2020-08-24 16:29
Unfortunately, nothing that easy. Only appearance of the PWK pieces (in MDL) is in the animation sequences.

**Comment by LaputianBird** [comment] 2020-08-24 18:36
Got curious and had a closer look - it seems to be that the naming convention for the use nodes is stricter than I thought - the nodes will be recognized if set to `le1_pwk_use01` and `le1_pwk_use02`, 13-char long - 12 or 14 already breaks it.
I don't know if anything changed recently, but either way it is dreadful, it means I'll have quite a few models to edit >.<

**Comment by Bill-Harper** [comment] 2020-08-24 18:42
Great catch! I gave the xp2 bif PWK a check and the pattern lines up. Last 3 letters on the mdl name when names were longer. Explains all the coded names we had to dig through, to figure out over the years. :)

**Comment by LaputianBird** [comment] 2020-08-24 19:06
I'm positive that it didn't show up before because either the placeable names usually were the standard BW length, which caused the use node to be 13-char long by as a consequence, or they were placeables mostly meant to be static (a lot, in my case) so there was no use case that exposed the issue. I wish it could be fixed in the mdl parsing code but I don't even dare asking it 💯

**Comment by LaputianBird** [comment] 2020-08-24 19:19
Sorry for spamming, I just thought I'd make sure I got it right once and for all - can you confirm that the naming convention is 13-char long, but unlike what I stated above, not only the `_use0[x]` part is required, but the pwk part to, so that the required suffix is actually `[any 4 characters]pwk_use0[x]` - if I replace `pwk` with any other character it breaks

**Comment by Bill-Harper** [comment] 2020-08-24 22:48
I'll run some tests tomorrow to verify what is possible, before committing to any heavy work, and let you know.

**Comment by LaputianBird** [comment] 2020-08-25 09:59
That's great - cheers

**Comment by Bill-Harper** [comment] 2020-08-25 10:31
It looks like any 3-character name will do (even on different nodes in the same PWK). The PWK node doesn't have to match the mdl name nor even be present in the MDL for use nodes and collision to work. With this sort of 'freedom' one could wonder why the strict 3/13-character requirement is even in place. But I've confirmed that a 4-character prefix does not work.

**Comment by LaputianBird** [comment] 2020-08-25 10:58
I think the engine always picks the closest to the character use node, which makes the numbering irrelevant in practical terms - I thought up to 4 nodes were recognized, but that might as well be another misconception, I don't recall anything that confirmed such assumption (maybe it comes from nwmax allowing up to 4)

**Closed** 2020-10-19 18:40 UTC
Labels: data
