### ISSUE TITLE
cursor click position sometimes offset

### ISSUE THREAD

**Issue by niv** [Beamdog/nwn-issues#8] opened 2020-01-27 13:27 UTC
* No reliable repro yet.
* When launching in maximised/fullscreen mode, sometimes the cursor click position is offset from the rendered icon.
* Resizing the window (triggering a reinit?) fixes.

**Comment by mtijanic** [comment] 2024-03-16 14:38
Let's say dupe of #551 which has a bit more info.

**Closed by mtijanic** 2024-03-16 14:38 UTC
Labels: game
