### ISSUE TITLE
GetEffectCasterLevel does not respect ArcSpellLvlMod and DivSpellLvlMod

### ISSUE THREAD

**Issue by catolm** [Beamdog/nwn-issues#416] opened 2021-11-27 14:36 UTC
GetEffectCasterLevel does not respect modifiers to ArcSpellLvlMod and DivSpellLvlMod.
The result is dispells having too strong effects against spells improved by these modifiers (such as pale master in the default classes2da)

This could have been easily worked around if there exited a SetEffectCasterLevel function, which would open for many other possibilities as well.

**Comment by Finaldeath** [comment] 2021-11-30 00:55
This is reported here if anyone wants more detail; https://github.com/Beamdog/nwn-issues/issues/207#

**Comment by Finaldeath** [comment] 2023-02-24 22:33
Duplicate of #207

**Closed by Finaldeath** 2023-02-24 22:33 UTC
