### ISSUE TITLE
Stunning Fist: uses per day refresh when a saved game is loaded

### ISSUE THREAD

**Issue by calgacus** [Beamdog/nwn-issues#327] opened 2021-05-24 20:54 UTC
**To Reproduce**

 
 - Play a monk 
 - use up your stunning fist attacks
 - save game
 - load that saved game
 - note that your remaining uses of stunning fist have increased (probably by 3).

**Specifics**

 - OS (Windows)
 - Game build ( .23)
 - Distro platform ( Steam)
 - Content overrides? ( Steam Workshop : many, but mainly just portrait paks)
 - Regression? ( unknown )
- Found while playing chp2 of the Aielund Saga with a  Monk/Sorc/RDD downloaded via the nwsync curated content system.

**Comment by DMSymphony** [comment] 2021-07-27 12:25
Cal,

I couldn't reproduce this in Prelude or Defender of the Crown in single player or multiplayer in .23 or .30.

I'm closing this issue for now, if you are still experiencing it, can you try a fresh settings.tml (move to desktop temporarily) and see if that changes it (server settings are contained in settings.tml), and if not, please post a .zip of the save within which you are restoring stunning fists?

Cheers.

**Closed by DMSymphony** 2021-07-27 12:25 UTC
Labels: game
