### ISSUE TITLE
1.83.8193.21 Many doors bugged e.g. City Exterior - Good Castle Door

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#286] opened 2021-03-19 15:59 UTC
Drawing your attention to Jira NWNS-8570 on advice from Julius Borisov.
Not sure why it's necessary to report Development release issues in two places?

**To Reproduce**

Start demo module.
Open door.
Clicking on the transition does not work unless the player moves slightly.

**Specifics**

Win10
1.83.8193.21
BDC
Repro Rate 100%
no custom content in demo

**If needed, describe the bug **
Same or similar issues with several different doors / doorway tiles.
- same issue with City Exterior double wall door
- some locked doors do not fire OnFailToOpen unless the player moves around and tries again
- some open transition doors do not work unless the player really hunts around for the sweet spot to stand before clicking
If warranted, add videos/screenshots to showcase the issue.
[_castle door bug.zip](https://github.com/Beamdog/nwn-issues/files/6172468/_castle.door.bug.zip)

**Comment by Proleric** [comment] 2021-03-20 08:43
Also affects rogue companions - response to locked door "I can't do that" - move a bit - response is Take20 > DC - door unlocked

**Comment by Soren217** [comment] 2021-03-21 08:56
Thanks for the report! 

Is this new to .21?

**Comment by Soren217** [comment] 2021-03-21 10:42
Actually, found the cause of the error, will be fixed in the next patch. :-)

**Closed by Soren217** 2021-03-21 10:42 UTC
Labels: game
