### ISSUE TITLE
Standard DDS flipped (compared to bioware DDS)

### ISSUE THREAD

**Issue by gyoerkaa** [Beamdog/nwn-issues#37] opened 2020-04-22 21:04 UTC
**To Reproduce**
 - Place attached files in Neverwinter Nights dir 
**Files:** [dds_test.zip](https://github.com/Beamdog/nwn-issues/files/4518990/dds_test.zip) (module + override)
 - Start module

**Specifics**
 - OS: Windows 10, Linux (probably all)
 - Game build: 8193.9
 - Distro platform: Steam

**Description**
- Standard DDS textures are flipped horizontally compared to bioware DDS format. 
- Happens both with DXT1 and DXT5 compression.
- Happens both in toolset and in-game
- Tested with dds from nwn crunch and nivida texture tools
- DDS have the correct orientation, when imported in Blender, photoshop or converted back to tga

Standard dds on the Left. Bioware dds on the Right
![dds_test_screenshot](https://user-images.githubusercontent.com/2905208/80033081-6b907900-84ec-11ea-83e5-12b19d3dee94.png)

**Comment by DMSymphony** [comment] 2020-04-24 08:40
That's not a bug, that's openGL, that's why the TGA flipper exists, because the DDS extractor exported "upside-down" textures.

All of the NWN DDS's are upside down, but you can't open them, so you don't know. The Bioware DDS tool flips the input before you start using it, because NWN uses openGL, so the artists expect an "upside-down" image to be used given the UV coordination, and the source art.

Crunch, not being specifically for NWN, doesn't do any flipping, so when you use Crunch for NWN, and using TGA as a source file, I recommend -unflip -yflip.

If you were doing non-openGL stuff, you don't want to flip.

All of the PLT's are upside-down also, if you could view them.

The TGA's have a Y reference at the 81's bit, so, if you are looking at Bioware's TGA's you can check to see if that bit is 0 or 1. If it's 1, then that means it's in like an "openGL" mode, which means it's upside-down, but anything you open it in to look at it will show it to you upside-down, so it will be right side up. NWN doesn't use it, except for portraits apparently, so it reads the TGA's in the game that don't have DDS's upside-down, which makes them the same as the DDS's.

The only thing that has changed here is that NWN can now use DDS files that weren't made with the auto-flipping Bioware DDS tool.

**Comment by LaputianBird** [comment] 2020-04-25 15:09
Pre-flipping the texture to compensate for the openGL expectations isn't really the best solution, albeit the one adopted by NWN many years ago.
The point of adding support for standard dds formats is exactly that of being able to use **standard** dds formats - if we need to pre-flip the textures anyway, then we could as well just use the nwn-specific dds format.
If we pre-flip, the supposedly standard dds textures would be rendered as flipped in any other program, as those don't expect any pre-flipping, and handle them properly according to the dds format specifications, as they should (in general, any openGL application is able to handle standard dds textures at runtime).

The solution is for NWN to also handle standard dds textures properly, meaning either to flip the texture when reading/loading from disk, or use the openGL function to flip the matrix at runtime. The issue might be that the nwn format is pre-flipped, so the engine would need to discriminate between .dds formats in order to call the extra function - however surely there is already a check for the dds header, to tell the two subtypes of dds apart from each other

**Comment by DMSymphony** [comment] 2020-04-25 15:57
I won't agree with most of this, the point of adding standard DDS formats allows for a wider range of tools. The entire nature of this report is incorrect, the standard DDS textures and the Bioware DDS textures are the same, there is no "they are upside-down", there is a first pixel (pixel block, if you really want to get into it) and a last pixel. The screenshots above show different DDS's, not NWN rendering the same thing two different ways.

If you wanted to arbitrarily un-OpenGL NWN's Non-Bioware DDS's, you could do that, but why you would bother with effort there and not acknowledge the need to do it for... well, all of the TGA's, the PLT's, the UV's, the Normal maps Y colors, the matrices, etc., is not obvious or rational.

NWN handles all textures properly. It puts the first pixel at the beginning. OpenGL has a different idea of what the beginning is, but this isn't some problem with an EE feature of adding support for reading DDS's created from dozens of tools instead of just the 20 year old Bioware one.

As above, if the "BioDDS" is somehow okay, because Bioware pre-baked in a -yflip for their artists into the converter (not the game), then you too can adopt -yflip into your workflow for non-Bioware tools, or you can be constrained to Bioware tools so they can do it for you.

Asset preparative restrictions aren't some new NWN phenomenon, the Bioware DDS tool is also perfectly capable of putting things in game upside-down compared to how the TGA's looked in Blender, or Max, or Photoshop, or whatever.

"Yeah, but, I don't have that problem because I make sure my textures have the right y orientation BEFORE I use the Bioware DDS tool, that's something that people figure out once they start making stuff".

Exactly.

**Comment by LaputianBird** [comment] 2020-04-25 16:18
There isn't a thing such as "openGL dds textures" - the dds textures are standardized, and all openGL applications handle dds textures properly, without needing them to be pre-flipped.
NWN is an exception, so yes, NWN doesn't handle dds textures properly. It uses a workaround, originating in a choice BW made at the time they implemented dds support.
It could be argued that it's too late to change it, but it doesn't make NWN handle dds textures any more "properly".
However, leaving it as it is would mean just introducing another nwn-specific standard even for dds that use the standard header, which is pointless and has no practical benefit - because the standard dds textures that the game now supposedly support would need to be flipped like the nwn-specific dds textures are - hence the game does not support standard dds textures.
It is so true that openGL implements functions specifically for handling the dds standard formats - but they need to be called by the openGL application

**Comment by DMSymphony** [comment] 2020-04-25 16:36
It is pointless. NWN doesn't have a DDS problem. Every texture does this. If you "save your TGA's properly for NWN" **you are the "workaround"** for TGA's rendering "improperly".

I'm not sure if you thought I said "OpenGL DDS", somewhere, since it doesn't sound like you're answering my reply at all, but I've declared quite clearly the opposite, that there is one format, and it's the engine you have a problem with.

Calling this "lack of standard DDS support" is silly and narrow. Write an angry email to Khronos.

If people have a problem because they are bothered by being able to see thumbnails of their DDS's for the first time and can now tell they are upside-down, without checking the binary like I did when I figured this stuff out, but the Bioware DDS's don't have thumbnails and the PLT's don't have thumbnails, so you can't tell they're also upside-down, that's not a regression, that's progress. Spread the word.

**Comment by LaputianBird** [comment] 2020-04-25 16:49
No no, you don't need to save TGA specifically for NWN - it reads standard tgas properly. It has a problem to read standard DDS textures though, as it is proved by the same textures being loaded properly by any other openGL application, except NWN.
Checking the binary has nothing to do with it, it only affects the way the data is stored in the file. But ANY openGL application that wants to load the standard DDS textures needs to Y-flip them at runtime.
Expecting the data stored in the file to be flipped is a lazy workaround, and breaks the concept of "supporting standard DDS" itself.

**Comment by virusman** [comment] 2020-05-07 19:24
@LaputianBird I think the main reason not to change this is because it's been like this for a long time, and flipping them now would flip all existing non-Bioware DDS textures, so it would be a breaking change.

**Comment by LaputianBird** [comment] 2020-05-08 08:48
@virusman That is a legitimate argument, not necessarily ideal, but certainly valid. Two remarks are necessary, though.

One, that there is a solution that keeps the current functionality for the existing NWN-specific DDS format, while allowing a different handling for the standard DDS formats, since the two have a different header - so in theory the engine could read the .dds file, check the header, and in case it's a standard format, flip the order of the data reading from disk. I'm aware that it adds overhead and it might be problematic depending on the technical constraints the game might have, but certainly it is a solution in line with what seems to be the standard of the openGL handling of such a case.

And two, that if it won't/can't be fixed for the reasons above, at least it should be concluded that NWN does **not** support standard DDS formats, as it makes the assumption that the raw data of the texture is pre-flipped, hence behaving in the exact opposite way as any other openGL application that reads the same texture files. It is at the very least misleading, and in practice breaks the workflow that it apparently supports, by introducing yet another NWN-specific DDS "format" that uses a standard header but flipped raw data (hence canceling out most of the benefit).

We can live with a "won't fix" sentence, but at times it's hard not to be bothered by yet another case of having to endure the consequences of a poor choice made by Bioware back in the day, and missing on the possibility to have more modern tools/workflows to work on custom content. Let alone not being bothered when we're told we're just imagining the problem because we're overly emotional artists.

**Comment by virusman** [comment] 2020-05-08 15:18
@LaputianBird Yes, such a check is possible, but it would break all existing content that is using standard DDS (pre-flipped). Unless it is possible to distinguish between new (not flipped) and old (pre-flipped) standard DDS, this change is 3 years too late. :(
Regarding the second point, while most OpenGL engines seem to prefer flipping textures at runtime, there is no standard specifying that it is the only proper way. In fact, if you google for “flipped dds texture”, you’ll find a lot of examples where DDS textures must be pre-flipped, including well-known games. That is the reason why most DDS converters have a -flip option.

**Comment by virusman** [comment] 2020-05-08 15:24
Here is a related thread in Blender: https://developer.blender.org/T59867
Unity seems to be pre-flipping DDS textures, among other things.

**Comment by LaputianBird** [comment] 2020-05-08 17:42
Yep I know that thread/issue - it seems to affect only the unity editor, the player is stated to handle it properly. The Unity resolution note says:
>The PVR compressed format does not allow Unity to flip the compressed image upon importing (in contrast to for example compressed DDS files, which Unity flips upon importing). Given that the default orientation of PVR textures does not match the required orientation of Unity, Unity renders these textures upside down. Hence Unity asks for flipped PVR textures
So it seems an issue only with a specific compressed format

In case of the DDS textures, I think these posts sum it up nicely:
> dds is, by definition, a DirectX format, meaning that DirectX defines the meaning of any settings. Any other system (such as OpenGL) that uses a different reference point must accommodate this: if the format states that 0,0 is the bottom left, then 0,0 is the bottom left, regardless of the system implementation. Otherwise, formats like PNG would be just as unusable.
> In other words, any open implementations that load DDS images upside down are incorrect.

>Blender does respect DDS format by doing expected vertical inversion, such that it can show DDS's in its OpenGL-based UV-mapping exactly as they would show in a native DirectX UV-mapping.

Overall, I found that openGL applications adopt one of these four main methods to handle the issue:
1. flipping the row order when reading the texture from disk
2. flipping the data in memory with a specific openGL function `stbi_set_flip_vertically_on_load(true);`
3. flipping the UV mapping
4. flipping the image in the shader
5. pre-flipping the image data when saving/converting the texture

`2` and `3` don't seem to be an option for NWN, because it'd need to take into account that the texture can come in different formats (tga or dds), and the engine reads them differently - it'd need to pass the info on the source to the openGL side, so the flipping would be performed only when needed
`4` seems expensive in terms of performance, and the shader would still need to know when a flipping is necessary (I believe the shader is fed an RGBA bitmap regardless of the source format)
`5` is what BW did, and what some game devs do as well (possibly in the attempt to optimize performance), but implies having total control on the asset formats and source - it makes sense for a game that isn't meant to support custom content, and can internally adopt any non-standard workflow. It doesn't seem to fit the case of NWN though.
`1` seems to be considered the appropriate way to handle DirectX formats in openGL, or in general any formats that use a different convention than what openGL expects.
Again, flipping the data based on the DDS header seems reasonable to me, but that is as far as I can go without knowing the specific implementation that something like that would require in NWN

**Comment by LaputianBird** [comment] 2020-05-08 17:48
Sorry I hadn't noticed your second-last reply, I got a notification only for the one that includes the link.

The check wouldn't break existing content, because NWN-specific .dds textures use a different header, different from the one part of the DDS standards. So it should be enough to discriminate

**Comment by virusman** [comment] 2020-05-08 17:52
Are you saying zero content was ever created for EE using standard DDS?

**Comment by LaputianBird** [comment] 2020-05-08 17:58
Yes, I'm pretty sure nobody ever used any standard DDS format yet, it's an addition that came with some recent patch

**Comment by LaputianBird** [comment] 2020-05-08 18:09
Found it in the 1.78 release notes:
`* The game now supports normal DDS textures without having to mangle the header.`

**Closed** 2023-04-21 12:58 UTC
Labels: game
