### ISSUE TITLE
Perfstats debug has a really long fadeout now when turned off

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#525] opened 2023-11-29 17:59 UTC
Perfstats debug has a really long fadeout now when turned off.   In previous previews it turned off instantly if I recall correctly.  Not sure if this is by design or not.  Seems fine overall, but just flagging it in case its not intended and a regression from previous previews.  Thanks.

**To Reproduce**

 - Run perfstats
 - Turn it off
 - It takes about 10 seconds or so to fade out. 

**Specifics**

 - OS Windows
 - Game build 36-6
 - Distro platform Steam
 - Content overrides? n
 - Regression? maybe

See the attached video.
 

https://github.com/Beamdog/nwn-issues/assets/62627607/c5211640-53b2-47bf-a4ee-65ea9de88581

**Comment by mtijanic** [comment] 2023-12-14 13:17
> It takes about 10 seconds or so to fade out.

By my highly scientific method of counting in my head, it takes 6s. The expected/default fade is 5s for all posted strings and nothing changed there. The extra 1s could maybe be from the time it takes to actually disable it since there's a thing that runs at 1Hz in the background thst may need to tick once.

Overall doesn't seem like something to fix and I don't think it's hiding a bigger regression or anything, so closing. Thanks for the diligence though!

**Closed by mtijanic** 2023-12-14 13:17 UTC
Labels: game
