### ISSUE TITLE
Placeable Attacked event executing inconsistently

### ISSUE THREAD

**Issue by aaronmfparr** [Beamdog/nwn-issues#35] opened 2020-04-15 02:03 UTC
**To Reproduce**
 - Load Attached module
- Attack the placeable
- look for text feedback: ATTACKED

**Specifics**
 - Windows,
 - Game build: 8193.10,
 - Steam, GOG

**If needed, describe the bug**
The OnPhysicalAttacked event is not executing or executing after a delay.

**Comment by aaronmfparr** [comment] 2020-04-15 02:05
[physcial_attacked_event.zip](https://github.com/Beamdog/nwn-issues/files/4478737/physcial_attacked_event.zip)

**Comment by aaronmfparr** [comment] 2020-04-25 17:01
This appears to be every objects Attack event.

**Comment by mtijanic** [comment] 2020-04-26 11:35
I think this is working as intended for me. ![](https://cdn.discordapp.com/attachments/386614619327954946/703931144571322398/unknown.png)

Every attack is coupled with the event firing. What does it look like on your end?

**Comment by aaronmfparr** [comment] 2020-05-17 18:34
This might be related to lower end hardware (within the specs recommended) testing game from toolset. Which suggests to me that there is a performance issue in newer version of NWN:EE because I did not have this problem prior to .10 and each version from there forward has it.

Does not appear when I am using the player client to play a module served by another computer.

**Comment by tinygiant98** [comment] 2023-03-17 00:49
@aaronmfparr Let me know within a week or so if this is still an issue with .35 and whatever system you're using nowadays.

**Comment by Finaldeath** [comment] 2023-03-17 21:45
Never test from the toolset it causes issues like events not firing / things going out of order. I think this can be closed @tinygiant98 since it is a F9 bug so marking it as such.

**Closed by Finaldeath** 2023-03-17 21:45 UTC
Labels: game
