### ISSUE TITLE
Linux Memory Leak after Area Transitions

### ISSUE THREAD

**Issue by ThuleanWizard** [Beamdog/nwn-issues#444] opened 2022-03-26 23:38 UTC
**To Reproduce**

 - Play game normally using the linux client.
 - Useless memory usage begins to accumulate
 - Useless memory usage begins to affect computer and game performance.
 - Computer Crash

**Specifics**

 - OS : (OpenSuSE Linux)
 - Game build: 8183.34
 - Distro platform: Steam
 - Content overrides? : None
 - Regression? : Unknown

**Details**

It also appears that certain distributions are not affected by this memory leak, as evidenced by this forum post. 
https://steamcommunity.com/app/704450/discussions/0/5116650215574855950/?l=spanish
Most of note is the occurrence of this bug on 'Pop!os', a Ubuntu based distribution.

**Comment by Script-Wrecked** [comment] 2022-12-21 07:18
This bug also occurs on:

- Ubuntu 22.04 | 86.8193.34.1 | Steam
- Fedora 37 Silverblue | 86.8193.34.1 | Steam

**Comment by Finaldeath** [comment] 2023-05-29 16:26
@ThuleanWizard @Script-Wrecked can you check this is still happening in either patch 35 (released to stable) or patch 36 which in preview - both contain some memory leak fixes and optimisations.

**Comment by mtijanic** [comment] 2024-02-24 11:28
As luck would have it, a different bug ended up causing https://github.com/Beamdog/nwn-issues/issues/579, which only ever reproduced on Mesa drivers. And while trying to understand why Mesa is special, we actually root caused this issue too. Any true fix has long missed the .36 window, but there is a solid workaround:

Option 1: Create a `~/.drirc` file and put this in it:
```XML
<driconf>
   <device>
      <!--
         Neverwinter Nights (and other Aurora Engine games) make many
         assumptions about the texture IDs range in use, which are not
         compatible with the way Mesa allocates them, so force Mesa to
         behave like most other drivers in this regard
      -->
      <application name="Neverwinter Nights" executable="nwmain-linux">
         <option name="force_gl_names_reuse" value="true"/>
      </application>
      <application name="Neverwinter Nights (WINE)" executable="nwmain.exe">
         <option name="force_gl_names_reuse" value="true"/>
      </application>
      <application name="Neverwinter Nights Aurora Toolset (WINE)" executable="nwtoolset.exe">
         <option name="force_gl_names_reuse" value="true"/>
      </application>
   </device>
</driconf>
```
If you already have such a file, you'll need to merge them - Copy the `<device>...</device>` bits into your file, immediately above your `</driconf>` line.


Option 2: Run the game with `force_gl_names_reuse=true ./nwmain-linux`.

You can put the special launch option into steam in the game's properties page. This will resolve both the memory leak and the performance drop, and unconfirmed reports also suggest it resolves other issues on Mesa.


This also explains why we weren't able to repro and why
> It also appears that certain distributions are not affected by this memory leak

Neither AMD nor NVIDIA proprietary drivers have this behavior. Nor do any of the Windows and Mac ones. 


Please test one of the above workarounds and report back if it resolved your issue.

**Comment by tgurr** [comment] 2024-02-26 17:39
> As luck would have it, a different bug ended up causing #579, which only ever reproduced on Mesa drivers. And while trying to understand why Mesa is special, we actually root caused this issue too. Any true fix has long missed the .36 window, but there is a solid workaround:
> 
> Option 1: Create a `~/.drirc` file and put this in it:
> 
> ```
> <driconf>
>    <device>
>       
>       <application name="Neverwinter Nights" executable="nwmain-linux">
>          <option name="force_gl_names_reuse" value="true"/>
>       </application>
>       <application name="Neverwinter Nights (WINE)" executable="nwmain.exe">
>          <option name="force_gl_names_reuse" value="true"/>
>       </application>
>       <application name="Neverwinter Nights Aurora Toolset (WINE)" executable="nwtoolset.exe">
>          <option name="force_gl_names_reuse" value="true"/>
>       </application>
>    </device>
> </driconf>
> ```
> 
> If you already have such a file, you'll need to merge them - Copy the `<device>...</device>` bits into your file, immediately above your `</driconf>` line.
> 
> Option 2: Run the game with `force_gl_names_reuse=true ./nwmain-linux`.
> 
> You can put the special launch option into steam in the game's properties page.
> 
> This will resolve both the memory leak and the performance drop, and unconfirmed reports also suggest it resolves other issues on Mesa.
> 
> This also explains why we weren't able to repro and why
> 
> > It also appears that certain distributions are not affected by this memory leak
> 
> Neither AMD nor NVIDIA proprietary drivers have this behavior. Nor do any of the Windows and Mac ones.
> 
> Please test one of the above workarounds and report back if it resolved your issue.

Just noticed the message and the reference to this issue on the latest changelog of the nwn:ee update on steam and from a quick search I couldn't find any upstream reference about this issue, @mtijanic would you be so kind to submit this upstream so it can be included in workarounds list mesa ships by itself by default? https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/util/00-mesa-defaults.conf

**Comment by mtijanic** [comment] 2024-02-26 17:53
Yes, it'll probably be PR'd upstream. It's still unclear what the feasibility of a proper fix is - if there's a reasonably simple way to make the game not depend on this behavior, it's better to patch the game. But I have a feeling it won't be so simple, so the workaround is likely here to stay.

But even if merged upstream, it'll take a long time for it to actually reach end users, so maybe a local workaround in the game itself is warranted.

**Comment by tgurr** [comment] 2024-02-26 19:17
> Yes, it'll probably be PR'd upstream. It's still unclear what the feasibility of a proper fix is - if there's a reasonably simple way to make the game not depend on this behavior, it's better to patch the game. But I have a feeling it won't be so simple, so the workaround is likely here to stay.
> 
> But even if merged upstream, it'll take a long time for it to actually reach end users, so maybe a local workaround in the game itself is warranted.

A proper fix in the game/engine would of course be great, maybe the mesa devs can also help to shed some light on it but looks like you know your stuff pretty well. I just want to mention that when looking to through the commits/branches/changelogs that driconf workarounds also happen to get backported to / cherrypicked for the previous mesa stable release updates as long as they're done by upstream so it could potentionally reach end users a little bit sooner, however clearly not as soon as a workaround in the game itself could provide. Thanks in advance for any work on this and nwn in general, I very much appreciate all of the work from passionate people keeping old classics alive and nwn:ee is an extraordinary example.

**Closed** 2024-04-09 08:17 UTC
Labels: game
