### ISSUE TITLE
Old 1.69 Drawn Transitions using DOOR and TAG no longer work in Enhanced Edition

### ISSUE THREAD

**Issue by PJHNWN** [Beamdog/nwn-issues#425] opened 2021-12-13 20:58 UTC
Old module builders from the Diamond Edition 1.69 Era used drawn area transition triggers with unique TAGs, and used the Door option for its Destination Type, despite said destination simply being another area transition trigger in another area.

This technique worked in the Diamond Edition 1.69 Era, and those modules which used the quirky technique are now all broken. 

The provided demo module was built using Diamond Edition 1.69 toolset where the transitions work and move the character from one area to the next. Loading the same demo module into Enhanced Edition to play, characters are unable to use the transition - it no longer appears.

Screenshot provided below of the BUG Module loaded in Diamond Edition 1.69 version with working area transition highlight.

![Calm before the Storm_169](https://user-images.githubusercontent.com/70107610/145887022-3c1ea97c-b927-4c79-a1bd-b850aa126922.jpg)

Screenshot provided below of the BUG Module loaded in Enhanced Edition .34 version with no area transition available.

![Calm before the Storm_EE](https://user-images.githubusercontent.com/70107610/145887181-720d37f4-55de-4176-860b-e400d838e0c0.jpg)

Archive of test BUG Module.

[BUG - OLD AT 169.zip](https://github.com/Beamdog/nwn-issues/files/7706930/BUG.-.OLD.AT.169.zip)

Thank-you too, for all these continued and excellent updates. May you all have a Merry Christmas and a great start to the New Year.

**Comment by Finaldeath** [comment] 2021-12-13 22:35
I'll add on debug-wise, the test module just shows the main bug so anything further isn't needed - that area transitions _don't even appear_ visually. I mean 1.69 isn't  great - you just go to the first "painted part" of the trigger but it at least does something and doesn't just deny you.

Looks like a regression in EE for sure. I assume some validation was added so that GetAreaTransitionTarget had to be a valid waypoint or door when previously it just didn't care - would be good to have the old behaviour restored.

**Comment by Finaldeath** [comment] 2023-02-24 22:39
Fixed in preview, although some regression still exists if it detects destination objects in a certain priority.

**Closed by Finaldeath** 2023-02-24 22:39 UTC
